// Transliteration of BizHawk's 6502 disassembler,
//   src/BizHawk.Emulation.Cores/CPUs/MOS 6502X/Disassembler.cs
// (BizHawk, MIT). Mnemonics, operand formatting and the " *" page-cross marks are kept character
// for character, so a trace line out of this core reads exactly like NesHawk's.
// Generated by waterbox/tools/gen-disasm.py -- do not hand-edit.

#pragma once

#include <cstdint>
#include <cstdio>

namespace nesDisasm
{

using PeekFn = uint8_t (*)(uint16_t);

inline uint16_t peekWord(uint16_t address, PeekFn peek)
{
  const uint8_t l = peek(address);
  const uint8_t h = peek((uint16_t)(address + 1));
  return (uint16_t)((h << 8) | l);
}

// Writes the disassembly of the instruction at `pc` into `out` and its length in bytes into
// `*length`. An opcode with no entry reads back as "???", one byte long, as in the original.
inline void disassemble(uint16_t pc, char *out, int outsz, PeekFn peek, int *length)
{
  const uint8_t op = peek(pc);
  switch (op)
  {
    case 0x00: *length = 1; snprintf(out, (size_t)outsz, "BRK"); return;
    case 0x01: *length = 2; snprintf(out, (size_t)outsz, "ORA ($%02X,X)", peek((uint16_t)(pc + 1))); return;
    case 0x04: *length = 2; snprintf(out, (size_t)outsz, "NOP $%02X", peek((uint16_t)(pc + 1))); return;
    case 0x05: *length = 2; snprintf(out, (size_t)outsz, "ORA $%02X", peek((uint16_t)(pc + 1))); return;
    case 0x06: *length = 2; snprintf(out, (size_t)outsz, "ASL $%02X", peek((uint16_t)(pc + 1))); return;
    case 0x08: *length = 1; snprintf(out, (size_t)outsz, "PHP"); return;
    case 0x09: *length = 2; snprintf(out, (size_t)outsz, "ORA #$%02X", peek((uint16_t)(pc + 1))); return;
    case 0x0A: *length = 1; snprintf(out, (size_t)outsz, "ASL A"); return;
    case 0x0C: *length = 3; snprintf(out, (size_t)outsz, "NOP ($%04X)", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x0D: *length = 3; snprintf(out, (size_t)outsz, "ORA $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x0E: *length = 3; snprintf(out, (size_t)outsz, "ASL $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x10: *length = 2; snprintf(out, (size_t)outsz, "BPL $%04X", (uint16_t)(pc + 2 + (int8_t)peek((uint16_t)(pc + 1)))); return;
    case 0x11: *length = 2; snprintf(out, (size_t)outsz, "ORA ($%02X),Y *", peek((uint16_t)(pc + 1))); return;
    case 0x14: *length = 2; snprintf(out, (size_t)outsz, "NOP $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0x15: *length = 2; snprintf(out, (size_t)outsz, "ORA $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0x16: *length = 2; snprintf(out, (size_t)outsz, "ASL $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0x18: *length = 1; snprintf(out, (size_t)outsz, "CLC"); return;
    case 0x19: *length = 3; snprintf(out, (size_t)outsz, "ORA $%04X,Y *", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x1A: *length = 1; snprintf(out, (size_t)outsz, "NOP"); return;
    case 0x1C: *length = 2; snprintf(out, (size_t)outsz, "NOP ($%02X,X)", peek((uint16_t)(pc + 1))); return;
    case 0x1D: *length = 3; snprintf(out, (size_t)outsz, "ORA $%04X,X *", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x1E: *length = 3; snprintf(out, (size_t)outsz, "ASL $%04X,X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x20: *length = 3; snprintf(out, (size_t)outsz, "JSR $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x21: *length = 2; snprintf(out, (size_t)outsz, "AND ($%02X,X)", peek((uint16_t)(pc + 1))); return;
    case 0x24: *length = 2; snprintf(out, (size_t)outsz, "BIT $%02X", peek((uint16_t)(pc + 1))); return;
    case 0x25: *length = 2; snprintf(out, (size_t)outsz, "AND $%02X", peek((uint16_t)(pc + 1))); return;
    case 0x26: *length = 2; snprintf(out, (size_t)outsz, "ROL $%02X", peek((uint16_t)(pc + 1))); return;
    case 0x28: *length = 1; snprintf(out, (size_t)outsz, "PLP"); return;
    case 0x29: *length = 2; snprintf(out, (size_t)outsz, "AND #$%02X", peek((uint16_t)(pc + 1))); return;
    case 0x2A: *length = 1; snprintf(out, (size_t)outsz, "ROL A"); return;
    case 0x2C: *length = 3; snprintf(out, (size_t)outsz, "BIT $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x2D: *length = 3; snprintf(out, (size_t)outsz, "AND $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x2E: *length = 3; snprintf(out, (size_t)outsz, "ROL $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x30: *length = 2; snprintf(out, (size_t)outsz, "BMI $%04X", (uint16_t)(pc + 2 + (int8_t)peek((uint16_t)(pc + 1)))); return;
    case 0x31: *length = 2; snprintf(out, (size_t)outsz, "AND ($%02X),Y *", peek((uint16_t)(pc + 1))); return;
    case 0x34: *length = 2; snprintf(out, (size_t)outsz, "NOP $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0x35: *length = 2; snprintf(out, (size_t)outsz, "AND $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0x36: *length = 2; snprintf(out, (size_t)outsz, "ROL $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0x38: *length = 1; snprintf(out, (size_t)outsz, "SEC"); return;
    case 0x39: *length = 3; snprintf(out, (size_t)outsz, "AND $%04X,Y *", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x3A: *length = 1; snprintf(out, (size_t)outsz, "NOP"); return;
    case 0x3C: *length = 2; snprintf(out, (size_t)outsz, "NOP ($%02X,X)", peek((uint16_t)(pc + 1))); return;
    case 0x3D: *length = 3; snprintf(out, (size_t)outsz, "AND $%04X,X *", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x3E: *length = 3; snprintf(out, (size_t)outsz, "ROL $%04X,X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x40: *length = 1; snprintf(out, (size_t)outsz, "RTI"); return;
    case 0x41: *length = 2; snprintf(out, (size_t)outsz, "EOR ($%02X,X)", peek((uint16_t)(pc + 1))); return;
    case 0x44: *length = 2; snprintf(out, (size_t)outsz, "NOP $%02X", peek((uint16_t)(pc + 1))); return;
    case 0x45: *length = 2; snprintf(out, (size_t)outsz, "EOR $%02X", peek((uint16_t)(pc + 1))); return;
    case 0x46: *length = 2; snprintf(out, (size_t)outsz, "LSR $%02X", peek((uint16_t)(pc + 1))); return;
    case 0x48: *length = 1; snprintf(out, (size_t)outsz, "PHA"); return;
    case 0x49: *length = 2; snprintf(out, (size_t)outsz, "EOR #$%02X", peek((uint16_t)(pc + 1))); return;
    case 0x4A: *length = 1; snprintf(out, (size_t)outsz, "LSR A"); return;
    case 0x4C: *length = 3; snprintf(out, (size_t)outsz, "JMP $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x4D: *length = 3; snprintf(out, (size_t)outsz, "EOR $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x4E: *length = 3; snprintf(out, (size_t)outsz, "LSR $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x50: *length = 2; snprintf(out, (size_t)outsz, "BVC $%04X", (uint16_t)(pc + 2 + (int8_t)peek((uint16_t)(pc + 1)))); return;
    case 0x51: *length = 2; snprintf(out, (size_t)outsz, "EOR ($%02X),Y *", peek((uint16_t)(pc + 1))); return;
    case 0x54: *length = 2; snprintf(out, (size_t)outsz, "NOP $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0x55: *length = 2; snprintf(out, (size_t)outsz, "EOR $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0x56: *length = 2; snprintf(out, (size_t)outsz, "LSR $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0x58: *length = 1; snprintf(out, (size_t)outsz, "CLI"); return;
    case 0x59: *length = 3; snprintf(out, (size_t)outsz, "EOR $%04X,Y *", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x5A: *length = 1; snprintf(out, (size_t)outsz, "NOP"); return;
    case 0x5C: *length = 2; snprintf(out, (size_t)outsz, "NOP ($%02X,X)", peek((uint16_t)(pc + 1))); return;
    case 0x5D: *length = 3; snprintf(out, (size_t)outsz, "EOR $%04X,X *", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x5E: *length = 3; snprintf(out, (size_t)outsz, "LSR $%04X,X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x60: *length = 1; snprintf(out, (size_t)outsz, "RTS"); return;
    case 0x61: *length = 2; snprintf(out, (size_t)outsz, "ADC ($%02X,X)", peek((uint16_t)(pc + 1))); return;
    case 0x64: *length = 2; snprintf(out, (size_t)outsz, "NOP $%02X", peek((uint16_t)(pc + 1))); return;
    case 0x65: *length = 2; snprintf(out, (size_t)outsz, "ADC $%02X", peek((uint16_t)(pc + 1))); return;
    case 0x66: *length = 2; snprintf(out, (size_t)outsz, "ROR $%02X", peek((uint16_t)(pc + 1))); return;
    case 0x68: *length = 1; snprintf(out, (size_t)outsz, "PLA"); return;
    case 0x69: *length = 2; snprintf(out, (size_t)outsz, "ADC #$%02X", peek((uint16_t)(pc + 1))); return;
    case 0x6A: *length = 1; snprintf(out, (size_t)outsz, "ROR A"); return;
    case 0x6C: *length = 3; snprintf(out, (size_t)outsz, "JMP ($%04X)", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x6D: *length = 3; snprintf(out, (size_t)outsz, "ADC $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x6E: *length = 3; snprintf(out, (size_t)outsz, "ROR $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x70: *length = 2; snprintf(out, (size_t)outsz, "BVS $%04X", (uint16_t)(pc + 2 + (int8_t)peek((uint16_t)(pc + 1)))); return;
    case 0x71: *length = 2; snprintf(out, (size_t)outsz, "ADC ($%02X),Y *", peek((uint16_t)(pc + 1))); return;
    case 0x74: *length = 2; snprintf(out, (size_t)outsz, "NOP $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0x75: *length = 2; snprintf(out, (size_t)outsz, "ADC $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0x76: *length = 2; snprintf(out, (size_t)outsz, "ROR $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0x78: *length = 1; snprintf(out, (size_t)outsz, "SEI"); return;
    case 0x79: *length = 3; snprintf(out, (size_t)outsz, "ADC $%04X,Y *", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x7A: *length = 1; snprintf(out, (size_t)outsz, "NOP"); return;
    case 0x7C: *length = 2; snprintf(out, (size_t)outsz, "NOP ($%02X,X)", peek((uint16_t)(pc + 1))); return;
    case 0x7D: *length = 3; snprintf(out, (size_t)outsz, "ADC $%04X,X *", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x7E: *length = 3; snprintf(out, (size_t)outsz, "ROR $%04X,X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x80: *length = 2; snprintf(out, (size_t)outsz, "NOP #$%02X", peek((uint16_t)(pc + 1))); return;
    case 0x81: *length = 2; snprintf(out, (size_t)outsz, "STA ($%02X,X)", peek((uint16_t)(pc + 1))); return;
    case 0x82: *length = 2; snprintf(out, (size_t)outsz, "NOP #$%02X", peek((uint16_t)(pc + 1))); return;
    case 0x84: *length = 2; snprintf(out, (size_t)outsz, "STY $%02X", peek((uint16_t)(pc + 1))); return;
    case 0x85: *length = 2; snprintf(out, (size_t)outsz, "STA $%02X", peek((uint16_t)(pc + 1))); return;
    case 0x86: *length = 2; snprintf(out, (size_t)outsz, "STX $%02X", peek((uint16_t)(pc + 1))); return;
    case 0x88: *length = 1; snprintf(out, (size_t)outsz, "DEY"); return;
    case 0x89: *length = 2; snprintf(out, (size_t)outsz, "NOP #$%02X", peek((uint16_t)(pc + 1))); return;
    case 0x8A: *length = 1; snprintf(out, (size_t)outsz, "TXA"); return;
    case 0x8C: *length = 3; snprintf(out, (size_t)outsz, "STY $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x8D: *length = 3; snprintf(out, (size_t)outsz, "STA $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x8E: *length = 3; snprintf(out, (size_t)outsz, "STX $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x90: *length = 2; snprintf(out, (size_t)outsz, "BCC $%04X", (uint16_t)(pc + 2 + (int8_t)peek((uint16_t)(pc + 1)))); return;
    case 0x91: *length = 2; snprintf(out, (size_t)outsz, "STA ($%02X),Y", peek((uint16_t)(pc + 1))); return;
    case 0x94: *length = 2; snprintf(out, (size_t)outsz, "STY $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0x95: *length = 2; snprintf(out, (size_t)outsz, "STA $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0x96: *length = 2; snprintf(out, (size_t)outsz, "STX $%02X,Y", peek((uint16_t)(pc + 1))); return;
    case 0x98: *length = 1; snprintf(out, (size_t)outsz, "TYA"); return;
    case 0x99: *length = 3; snprintf(out, (size_t)outsz, "STA $%04X,Y", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0x9A: *length = 1; snprintf(out, (size_t)outsz, "TXS"); return;
    case 0x9D: *length = 3; snprintf(out, (size_t)outsz, "STA $%04X,X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xA0: *length = 2; snprintf(out, (size_t)outsz, "LDY #$%02X", peek((uint16_t)(pc + 1))); return;
    case 0xA1: *length = 2; snprintf(out, (size_t)outsz, "LDA ($%02X,X)", peek((uint16_t)(pc + 1))); return;
    case 0xA2: *length = 2; snprintf(out, (size_t)outsz, "LDX #$%02X", peek((uint16_t)(pc + 1))); return;
    case 0xA4: *length = 2; snprintf(out, (size_t)outsz, "LDY $%02X", peek((uint16_t)(pc + 1))); return;
    case 0xA5: *length = 2; snprintf(out, (size_t)outsz, "LDA $%02X", peek((uint16_t)(pc + 1))); return;
    case 0xA6: *length = 2; snprintf(out, (size_t)outsz, "LDX $%02X", peek((uint16_t)(pc + 1))); return;
    case 0xA8: *length = 1; snprintf(out, (size_t)outsz, "TAY"); return;
    case 0xA9: *length = 2; snprintf(out, (size_t)outsz, "LDA #$%02X", peek((uint16_t)(pc + 1))); return;
    case 0xAA: *length = 1; snprintf(out, (size_t)outsz, "TAX"); return;
    case 0xAC: *length = 3; snprintf(out, (size_t)outsz, "LDY $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xAD: *length = 3; snprintf(out, (size_t)outsz, "LDA $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xAE: *length = 3; snprintf(out, (size_t)outsz, "LDX $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xB0: *length = 2; snprintf(out, (size_t)outsz, "BCS $%04X", (uint16_t)(pc + 2 + (int8_t)peek((uint16_t)(pc + 1)))); return;
    case 0xB1: *length = 2; snprintf(out, (size_t)outsz, "LDA ($%02X),Y *", peek((uint16_t)(pc + 1))); return;
    case 0xB3: *length = 2; snprintf(out, (size_t)outsz, "LAX ($%02X),Y *", peek((uint16_t)(pc + 1))); return;
    case 0xB4: *length = 2; snprintf(out, (size_t)outsz, "LDY $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0xB5: *length = 2; snprintf(out, (size_t)outsz, "LDA $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0xB6: *length = 2; snprintf(out, (size_t)outsz, "LDX $%02X,Y", peek((uint16_t)(pc + 1))); return;
    case 0xB8: *length = 1; snprintf(out, (size_t)outsz, "CLV"); return;
    case 0xB9: *length = 3; snprintf(out, (size_t)outsz, "LDA $%04X,Y *", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xBA: *length = 1; snprintf(out, (size_t)outsz, "TSX"); return;
    case 0xBC: *length = 3; snprintf(out, (size_t)outsz, "LDY $%04X,X *", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xBD: *length = 3; snprintf(out, (size_t)outsz, "LDA $%04X,X *", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xBE: *length = 3; snprintf(out, (size_t)outsz, "LDX $%04X,Y *", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xC0: *length = 2; snprintf(out, (size_t)outsz, "CPY #$%02X", peek((uint16_t)(pc + 1))); return;
    case 0xC1: *length = 2; snprintf(out, (size_t)outsz, "CMP ($%02X,X)", peek((uint16_t)(pc + 1))); return;
    case 0xC2: *length = 2; snprintf(out, (size_t)outsz, "NOP #$%02X", peek((uint16_t)(pc + 1))); return;
    case 0xC4: *length = 2; snprintf(out, (size_t)outsz, "CPY $%02X", peek((uint16_t)(pc + 1))); return;
    case 0xC5: *length = 2; snprintf(out, (size_t)outsz, "CMP $%02X", peek((uint16_t)(pc + 1))); return;
    case 0xC6: *length = 2; snprintf(out, (size_t)outsz, "DEC $%02X", peek((uint16_t)(pc + 1))); return;
    case 0xC8: *length = 1; snprintf(out, (size_t)outsz, "INY"); return;
    case 0xC9: *length = 2; snprintf(out, (size_t)outsz, "CMP #$%02X", peek((uint16_t)(pc + 1))); return;
    case 0xCA: *length = 1; snprintf(out, (size_t)outsz, "DEX"); return;
    case 0xCB: *length = 2; snprintf(out, (size_t)outsz, "AXS $%02X", peek((uint16_t)(pc + 1))); return;
    case 0xCC: *length = 3; snprintf(out, (size_t)outsz, "CPY $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xCD: *length = 3; snprintf(out, (size_t)outsz, "CMP $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xCE: *length = 3; snprintf(out, (size_t)outsz, "DEC $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xD0: *length = 2; snprintf(out, (size_t)outsz, "BNE $%04X", (uint16_t)(pc + 2 + (int8_t)peek((uint16_t)(pc + 1)))); return;
    case 0xD1: *length = 2; snprintf(out, (size_t)outsz, "CMP ($%02X),Y *", peek((uint16_t)(pc + 1))); return;
    case 0xD4: *length = 2; snprintf(out, (size_t)outsz, "NOP $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0xD5: *length = 2; snprintf(out, (size_t)outsz, "CMP $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0xD6: *length = 2; snprintf(out, (size_t)outsz, "DEC $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0xD8: *length = 1; snprintf(out, (size_t)outsz, "CLD"); return;
    case 0xD9: *length = 3; snprintf(out, (size_t)outsz, "CMP $%04X,Y *", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xDA: *length = 1; snprintf(out, (size_t)outsz, "NOP"); return;
    case 0xDC: *length = 2; snprintf(out, (size_t)outsz, "NOP ($%02X,X)", peek((uint16_t)(pc + 1))); return;
    case 0xDD: *length = 3; snprintf(out, (size_t)outsz, "CMP $%04X,X *", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xDE: *length = 3; snprintf(out, (size_t)outsz, "DEC $%04X,X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xE0: *length = 2; snprintf(out, (size_t)outsz, "CPX #$%02X", peek((uint16_t)(pc + 1))); return;
    case 0xE1: *length = 2; snprintf(out, (size_t)outsz, "SBC ($%02X,X)", peek((uint16_t)(pc + 1))); return;
    case 0xE2: *length = 2; snprintf(out, (size_t)outsz, "NOP #$%02X", peek((uint16_t)(pc + 1))); return;
    case 0xE4: *length = 2; snprintf(out, (size_t)outsz, "CPX $%02X", peek((uint16_t)(pc + 1))); return;
    case 0xE5: *length = 2; snprintf(out, (size_t)outsz, "SBC $%02X", peek((uint16_t)(pc + 1))); return;
    case 0xE6: *length = 2; snprintf(out, (size_t)outsz, "INC $%02X", peek((uint16_t)(pc + 1))); return;
    case 0xE8: *length = 1; snprintf(out, (size_t)outsz, "INX"); return;
    case 0xE9: *length = 2; snprintf(out, (size_t)outsz, "SBC #$%02X", peek((uint16_t)(pc + 1))); return;
    case 0xEA: *length = 1; snprintf(out, (size_t)outsz, "NOP"); return;
    case 0xEC: *length = 3; snprintf(out, (size_t)outsz, "CPX $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xED: *length = 3; snprintf(out, (size_t)outsz, "SBC $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xEE: *length = 3; snprintf(out, (size_t)outsz, "INC $%04X", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xF0: *length = 2; snprintf(out, (size_t)outsz, "BEQ $%04X", (uint16_t)(pc + 2 + (int8_t)peek((uint16_t)(pc + 1)))); return;
    case 0xF1: *length = 2; snprintf(out, (size_t)outsz, "SBC ($%02X),Y *", peek((uint16_t)(pc + 1))); return;
    case 0xF4: *length = 2; snprintf(out, (size_t)outsz, "NOP $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0xF5: *length = 2; snprintf(out, (size_t)outsz, "SBC $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0xF6: *length = 2; snprintf(out, (size_t)outsz, "INC $%02X,X", peek((uint16_t)(pc + 1))); return;
    case 0xF8: *length = 1; snprintf(out, (size_t)outsz, "SED"); return;
    case 0xF9: *length = 3; snprintf(out, (size_t)outsz, "SBC $%04X,Y *", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xFA: *length = 1; snprintf(out, (size_t)outsz, "NOP"); return;
    case 0xFC: *length = 2; snprintf(out, (size_t)outsz, "NOP ($%02X,X)", peek((uint16_t)(pc + 1))); return;
    case 0xFD: *length = 3; snprintf(out, (size_t)outsz, "SBC $%04X,X *", peekWord((uint16_t)(pc + 1), peek)); return;
    case 0xFE: *length = 3; snprintf(out, (size_t)outsz, "INC $%04X,X", peekWord((uint16_t)(pc + 1), peek)); return;
  }
  *length = 1;
  snprintf(out, (size_t)outsz, "???");
}

} // namespace nesDisasm
