#!/usr/bin/env python3
# Generates audioKernel.hpp: the band-limited step kernel the audio resampler uses.
#
# The APU emits a stream of DELTAS - "the mixed output changed by this much, at this CPU cycle".
# Turning that into 44.1kHz samples is not decimation, because an edge between two output samples
# carries energy far above the output Nyquist: point-sampled, it folds back as audible tones, and
# where it folds depends on exactly when the edge happened rather than on the music. The standard
# treatment (band-limited step synthesis) gives every delta a band-limited impulse spread over a few
# output samples, sums those, and integrates once at the end - the integral of a band-limited
# impulse being a band-limited step, which is what the analogue side of a console produces anyway.
#
# So this table is one lowpass impulse response per sub-sample position: the inverse transform of
# the response we want,
#
#   h(x) = 2 * integral(0..C) G(f) cos(2 pi f x) df,   G(f) = 1 / sqrt(1 + (f * FS / FC) ^ 2)
#
# sampled at x = (j - (HALF_WIDTH - 1)) - f for tap j, where f = phase / PHASE_COUNT says where the
# delta fell between two output samples, then windowed (a truncated impulse response rings).
#
# C, the cutoff, sits just under the output Nyquist: at exactly Nyquist the images fold back around
# 13dB louder, measured. G is a first-order treble rolloff at FC. That is EQ, not filtering the
# resampler needs - it is there because it matches the treble of the reference implementation this
# replaced (blip_buf, and so BizHawk, and so what a NesHawk recording sounds like) to within half a
# decibel from DC to 18kHz. Shaping the kernel rather than filtering the output afterwards keeps the
# phase linear, which a one-pole filter would not.
#
# One row past PHASE_COUNT is emitted, holding phase 1.0, so the resampler can interpolate between
# two rows instead of quantising a delta to the nearest 1/32 of a sample. That is worth about 11dB
# of noise floor and costs one extra row.
#
# Each row is scaled to KERNEL_UNIT and then corrected to sum to KERNEL_UNIT EXACTLY. That is not
# cosmetic: the reader integrates, so a row summing to 65535 would leave a fraction of every delta
# in the integrator forever, and the error would pile up into audible DC drift.
#
# The table is generated rather than computed at startup because it must be identical in every
# build: the equivalence gate compares audio between a glibc host build and a musl guest build, and
# two libm's may not agree on the last bit of sin().
#
# Usage: gen-audio-kernel.py [output.hpp]

import math
import os
import sys

PHASE_COUNT = 32     # sub-sample positions; the resampler interpolates between adjacent ones
HALF_WIDTH = 8       # taps each side of the impulse
WIDTH = HALF_WIDTH * 2
KERNEL_UNIT = 1 << 16
CUTOFF = 0.92        # passband edge, as a fraction of the output Nyquist
SAMPLE_RATE = 44100.0
TREBLE_CORNER = 10000.0  # first-order rolloff corner, chosen to match the reference's treble
INTEGRATION_STEPS = 2048

out_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), "..", "audioKernel.hpp")


def impulse(x):
    """2 * integral of the desired magnitude response against cos(2 pi f x), by trapezoid."""
    c = CUTOFF * 0.5  # cycles per output sample
    total = 0.0
    for i in range(INTEGRATION_STEPS + 1):
        f = c * i / INTEGRATION_STEPS
        gain = 1.0 / math.sqrt(1.0 + (f * SAMPLE_RATE / TREBLE_CORNER) ** 2)
        weight = 0.5 if i in (0, INTEGRATION_STEPS) else 1.0
        total += weight * gain * math.cos(2.0 * math.pi * f * x)
    return 2.0 * total * (c / INTEGRATION_STEPS)


def blackman(t):
    # t in [-1, 1]
    a = math.pi * (t + 1.0)
    return 0.42 - 0.5 * math.cos(a) + 0.08 * math.cos(2.0 * a)


rows = []
for phase in range(PHASE_COUNT + 1):  # inclusive: the last row is phase 1.0, for interpolation
    f = phase / PHASE_COUNT
    taps = []
    for j in range(WIDTH):
        x = (j - (HALF_WIDTH - 1)) - f
        taps.append(impulse(x) * blackman(x / HALF_WIDTH))
    total = sum(taps)
    scaled = [int(round(t * KERNEL_UNIT / total)) for t in taps]
    # hand the rounding error to the largest tap, where it is relatively smallest
    error = KERNEL_UNIT - sum(scaled)
    scaled[max(range(WIDTH), key=lambda i: abs(scaled[i]))] += error
    assert sum(scaled) == KERNEL_UNIT
    rows.append(scaled)

body = "".join(
    "  { " + ", ".join("%6d" % v for v in row) + " },\n" for row in rows
)

open(out_path, "w").write(
    f"""// Band-limited step kernel for the audio resampler: one lowpass impulse response per sub-sample
// position, so a delta that falls between two output samples still lands where it belongs. Each row
// sums to exactly {KERNEL_UNIT}, and one row past the last phase exists so the resampler can interpolate.
// Generated by waterbox/tools/gen-audio-kernel.py -- do not hand-edit. The maths is documented there.

#pragma once

#include <cstdint>

namespace audioKernel
{{

constexpr int PhaseCount = {PHASE_COUNT};
constexpr int PhaseBits = {PHASE_COUNT.bit_length() - 1};
constexpr int HalfWidth = {HALF_WIDTH};
constexpr int Width = {WIDTH};
constexpr int Unit = {KERNEL_UNIT};
constexpr int UnitShift = {KERNEL_UNIT.bit_length() - 1};

inline const int32_t Impulse[PhaseCount + 1][Width] = {{
{body}}};

}} // namespace audioKernel
"""
)
print(f"wrote {os.path.normpath(out_path)} ({PHASE_COUNT} phases x {WIDTH} taps)")
