#!/usr/bin/env python3
# Regenerates nesPalettes.hpp from BizHawk's Palettes.cs, so the picture comes out of this core in
# exactly the colours NesHawk uses. The C# tables are plain brace-delimited RGB triples, some of
# them written as `value<<SHIFT`, which python can evaluate directly.
#
# Usage: gen-palettes.py <BizHawk checkout> [output.hpp]

import os
import re
import sys

bizhawk = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/BizHawk")
out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), "..", "nesPalettes.hpp")
src_path = os.path.join(bizhawk, "src/BizHawk.Emulation.Cores/Consoles/Nintendo/NES/Palettes.cs")

src = open(src_path).read()
shift = int(re.search(r"private const int SHIFT = (\d+);", src).group(1))
tables = re.findall(r"public static readonly byte\[,\] (\w+)\s*=\s*\{(.*?)\n\t\t\};", src, re.S)
if not tables:
    sys.exit(f"no palettes found in {src_path}")

chunks = []
for name, body in tables:
    entries = []
    for triple in re.findall(r"\{([^}]*)\}", body):
        rgb = [eval(part.strip().replace("SHIFT", str(shift))) for part in triple.split(",")]
        if len(rgb) != 3:
            sys.exit(f"{name}: expected RGB triples, got {triple!r}")
        entries.append(rgb)
    if len(entries) != 64:
        sys.exit(f"{name}: expected 64 colours, got {len(entries)}")
    rows = "".join("  { %3d, %3d, %3d },\n" % tuple(e) for e in entries)
    chunks.append(f"inline const uint8_t {name}[64][3] = {{\n{rows}}};\n")
    print(f"{name}: {len(entries)} colours")

open(out_path, "w").write(
    """// The palettes NesHawk ships, transcribed from
//   src/BizHawk.Emulation.Cores/Consoles/Nintendo/NES/Palettes.cs
// (BizHawk, MIT). Each is 64 RGB triples; applyDeemphasis expands one into the 512 entries the PPU
// can actually address (6 colour bits plus the 3 emphasis bits).
// Generated by waterbox/tools/gen-palettes.py -- do not hand-edit.

#pragma once

#include <cstdint>

namespace nesPalettes
{

"""
    + "\n".join(chunks)
    + """
// Palettes.cs ApplyDeemphasis. The comment there ("DEEMPH BITS MAY BE ORDERED WRONG") is BizHawk's
// own; the numbers are kept as they are, since matching NesHawk is the point.
inline void applyDeemphasis(int &r, int &g, int &b, int deemphBits)
{
  static const float rtmul[] = { 1.239f, 0.794f, 1.019f, 0.905f, 1.023f, 0.741f, 0.75f };
  static const float gtmul[] = { 0.915f, 1.086f, 0.980f, 1.026f, 0.908f, 0.987f, 0.75f };
  static const float btmul[] = { 0.743f, 0.882f, 0.653f, 1.277f, 0.979f, 0.101f, 0.75f };
  if (deemphBits == 0) return;
  const int d = deemphBits - 1;
  r = (int)(r * rtmul[d]);
  g = (int)(g * gtmul[d]);
  b = (int)(b * btmul[d]);
  if (r > 0xFF) r = 0xFF;
  if (g > 0xFF) g = 0xFF;
  if (b > 0xFF) b = 0xFF;
}

} // namespace nesPalettes
"""
)
print(f"wrote {os.path.normpath(out_path)}")
