#!/usr/bin/env python3
# Regenerates nes6502Disasm.hpp from BizHawk's own 6502 disassembler, so the trace logger prints
# exactly what NesHawk prints. The C# is one flat switch of interpolated string literals, which
# transliterates mechanically; anything the three known interpolation forms do not cover is a hard
# error rather than a silent omission.
#
# Usage: gen-disasm.py <BizHawk checkout> [output.hpp]

import os
import re
import sys

bizhawk = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/BizHawk")
out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), "..", "nes6502Disasm.hpp")
src_path = os.path.join(bizhawk, "src/BizHawk.Emulation.Cores/CPUs/MOS 6502X/Disassembler.cs")

src = open(src_path).read()
cases = re.findall(r'case (0x[0-9A-Fa-f]{2}): bytesToAdvance = (\d+); return (\$?"[^;]*");', src)
if len(cases) != 180:
    sys.exit(f"expected 180 opcodes in {src_path}, found {len(cases)}")

# ({regex}, C++ argument): the operand forms the C# uses. "$" is literal text in an interpolated
# string (it is the hex prefix), only "{...}" is a hole.
FORMS = [
    (r'\{peeker\(\+\+pc\):X2\}', "%02X", "peek((uint16_t)(pc + 1))"),
    (r'\{peeker_word\(\+\+pc, peeker\):X4\}', "%04X", "peekWord((uint16_t)(pc + 1), peek)"),
    (r'\{\(ushort\)\(pc \+ 2 \+ \(sbyte\)peeker\(\+\+pc\)\):X4\}', "%04X",
     "(uint16_t)(pc + 2 + (int8_t)peek((uint16_t)(pc + 1)))"),
]

lines = []
for op, length, literal in cases:
    interpolated = literal.startswith("$")
    body = literal[2:-1] if interpolated else literal[1:-1]
    arg = None
    if interpolated:
        for pattern, spec, expr in FORMS:
            m = re.search(pattern, body)
            if m:
                body = body[: m.start()] + spec + body[m.end() :]
                arg = expr
                break
        if "{" in body:
            sys.exit(f"unhandled interpolation in opcode {op}: {literal}")
    body = body.replace("\\", "\\\\").replace('"', '\\"')
    call = f'snprintf(out, (size_t)outsz, "{body}"' + (f", {arg}" if arg else "") + ");"
    lines.append(f"    case {op}: *length = {length}; {call} return;")

open(out_path, "w").write(
    """// Transliteration of BizHawk's 6502 disassembler,
//   src/BizHawk.Emulation.Cores/CPUs/MOS 6502X/Disassembler.cs
// (BizHawk, MIT). Mnemonics, operand formatting and the " *" page-cross marks are kept character
// for character, so a trace line out of this core reads exactly like NesHawk's.
// Generated by waterbox/tools/gen-disasm.py -- do not hand-edit.

#pragma once

#include <cstdint>
#include <cstdio>

namespace nesDisasm
{

using PeekFn = uint8_t (*)(uint16_t);

inline uint16_t peekWord(uint16_t address, PeekFn peek)
{
  const uint8_t l = peek(address);
  const uint8_t h = peek((uint16_t)(address + 1));
  return (uint16_t)((h << 8) | l);
}

// Writes the disassembly of the instruction at `pc` into `out` and its length in bytes into
// `*length`. An opcode with no entry reads back as "???", one byte long, as in the original.
inline void disassemble(uint16_t pc, char *out, int outsz, PeekFn peek, int *length)
{
  const uint8_t op = peek(pc);
  switch (op)
  {
"""
    + "\n".join(lines)
    + """
  }
  *length = 1;
  snprintf(out, (size_t)outsz, "???");
}

} // namespace nesDisasm
"""
)
print(f"wrote {os.path.normpath(out_path)} ({len(cases)} opcodes)")
